[package]
name = "ansi-multiple"
version = "0.1.0"
authors = ["Ship <michael.shiplet@vivint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
chrono = "0.2.16"
terminal_size = "0.1.10"
